development: &default
  adapter: sqlite3
  database: db/abirds_development.db

test: &test
  <<: *default
  database: db/abirds_test.db

cucumber:
  <<: *test
  
production: 
  encoding: unicode
  adapter: postgresql
  username: yyinvjiyhl
  port: 5432
  host: ec2-174-129-3-52.compute-1.amazonaws.com
  database: yyinvjiyhl
  password: cGhE6y-pog1Cg81qcgKg